name = "a1-property-services"
pages_build_output_dir = "out"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "/api/reviews"
zone_id = ""

[[routes]]
pattern = "/api/reindex"
zone_id = ""
